#!/bin/bash

HALO_TEST_LOG=${HALO_TEST_LOG:-/dev/stdout}

res_state_file="tests/test_output/$HALO_TEST_ID/lustre.$(echo $OCF_RESKEY_mountpoint | tr / _)"

start () {
	echo lustre start mountpoint=$OCF_RESKEY_mountpoint target=$OCF_RESKEY_target >> $HALO_TEST_LOG
	touch $res_state_file || exit 1
	exit 0
}

stop () {
	echo lustre stop mountpoint=$OCF_RESKEY_mountpoint target=$OCF_RESKEY_target >> $HALO_TEST_LOG
	rm -f $res_state_file
	exit 0
}

monitor () {
	echo lustre monitor mountpoint=$OCF_RESKEY_mountpoint target=$OCF_RESKEY_target >> $HALO_TEST_LOG
	if [ -f "$res_state_file" ]; then
		exit 0
	else
		exit 7
	fi
}

no_such_command() {
	echo "No such command"
	exit 1
}

case $1 in
    start)              start;;
    stop)               stop;;
    status|monitor)     monitor;;
    *)                  no_such_command;;
esac
